#pracitce code for a main menu, as recommneded by tutor.
print("Select from the following choices:\n")
print("0: Exit\n")
print("1: Submit helpdesk ticket\n")
print("2: Show all tickets\n")
print("3: Respond to ticket by number\n")
print("4: Re-open resolved ticket\n")
print("5: Display ticket stats\n")
print("----------------------------------\n")
menu_selection = int(input("Enter menu selection 0 - 5 :\n"))
